version: '2'

services:

  mybunkerized:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bunkerized-certs:/etc/letsencrypt
      #- ./www:/www:ro
      - bunkerized-vol:/etc/nginx
      - ./confs/server-confs:/server-confs:ro
      - ./confs/modsec-crs-confs:/modsec-crs-confs:ro
      - ./confs/modsec-confs:/modsec-confs:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - MULTISITE=yes
      - LISTEN_HTTP=yes
      - USE_WHITELIST_IP=${USE_WHITELIST_IP}
      - WHITELIST_IP_LIST=${WHITELIST_IP_LIST}
      - USE_WHITELIST_REVERSE=${USE_WHITELIST_REVERSE}
      - WHITELIST_REVERSE_LIST=${WHITELIST_REVERSE_LIST}
      - LOG_LEVEL=${LOG_LEVEL}
      - USE_MODSECURITY=${USE_MODSECURITY}
      - USE_BAD_BEHAVIOR=${USE_BAD_BEHAVIOR}
      - USE_MODSECURITY_CRS=${USE_MODSECURITY_CRS}
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - services-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes_from:
      - mybunkerized
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mybunkerized
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  bunkerized-vol:
  bunkerized-certs:

networks:
  services-net:
    external: true
